name: Build and Push Docker image to Docker Hub

on: push
jobs:
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create kubeconfig
      run: |
        echo ${{ secrets.KUBE_CONFIG }}
    - name: Deploy to K8s
      run: kubectl apply -f k8s-node-app.yaml
